[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_extension = "2A4udxjXYzZnJgX65cbVpr3421bpWrrjUBNey1iWrEiy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/urvesh109/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
