[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_extension = "2A4udxjXYzZnJgX65cbVpr3421bpWrrjUBNey1iWrEiy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "keypairs/admin.json"

[scripts]
mint-close = "DEBUG=log:* yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/mintCloseAuthority.ts"
transfer = "DEBUG=log:* yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/transferFee.ts"
default = "DEBUG=log:* yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/defaultState.ts"
immutable = "DEBUG=log:* yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/immutableOwner.ts"
non = "DEBUG=log:* yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/nonTransferable.ts"
