[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
opaque = "GFZBH5E5peCPF6KZPzXQpx4YiWmqSwMZHsmG1yF9fvai"
token_extension = "2A4udxjXYzZnJgX65cbVpr3421bpWrrjUBNey1iWrEiy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "keypairs/admin.json"

[scripts]
cpi = "DEBUG=log:* yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/cpiGuard.ts && exit 0"
default = "DEBUG=log:* yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/defaultState.ts && exit 0"
immutable = "DEBUG=log:* yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/immutableOwner.ts && exit 0"
interest = "DEBUG=log:* yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/interestBearing.ts && exit 0"
memo = "DEBUG=log:* yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/memoEnable.ts && exit 0"
mint-close = "DEBUG=log:* yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/mintCloseAuthority.ts && exit 0"
non = "DEBUG=log:* yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/nonTransferable.ts && exit 0"
permanent = "DEBUG=log:* yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/permanentDelegate.ts && exit 0"
realloc = "DEBUG=log:* yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/realloc.ts && exit 0"
transfer = "DEBUG=log:* yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/transferFee.ts && exit 0"
